### ISSUE TITLE
Slight variance drift compared to abcrf

### ISSUE THREAD

**Issue by fradav** [diyabc/abcranger#24]
Distributions comparisons

![expectations_comparison](https://user-images.githubusercontent.com/701587/60105474-a65a4100-9763-11e9-9111-d53d9d7bec25.png)
![variances_comparison](https://user-images.githubusercontent.com/701587/60105568-d1dd2b80-9763-11e9-9548-25fb0afd0d52.png)

**Comment by fradav** [comment]
My first guess is that rf parameters are not completely aligned with abcrf' ones. We should double-check them.

**Comment by fradav** [comment]
Fixed in : https://github.com/diyabc/abcranger/commit/4e20b6631e8172e5ac9c44955872f421c53cc423
All ks test passed for expectations, variances and quantiles.

![expectation_comparison5](https://user-images.githubusercontent.com/701587/60503098-4dd4f780-9cbf-11e9-86ca-db296f1be3f1.png)
![variances_comparison5](https://user-images.githubusercontent.com/701587/60503114-55949c00-9cbf-11e9-99b7-a56fb96e0acc.png)

**Comment by aestoup** [comment]
Variance pbl fixed!!! Congratulation.
