### ISSUE TITLE
Slight bias in model choice post proba

### ISSUE THREAD

**Issue by fradav** [diyabc/abcranger#28]
I made one manually, should be automatized in test function as it is already for estimparam

**Comment by fradav** [comment]
Ks test for model choice fails miserably but look at this :

![postproba_comparison](https://user-images.githubusercontent.com/701587/60592446-f1e29f80-9da0-11e9-92eb-baf597855bcb.png)

![postproba_boxplots_comparison](https://user-images.githubusercontent.com/701587/60592455-f5762680-9da0-11e9-9f35-7ad79bc44eda.png)

We are not too bad ?

**Comment by aestoup** [comment]
Question / intuition: could the origin of this bias be "the same as" the one (resolved) for EstimParam?

**Comment by fradav** [comment]
The problem for EstimParam was a trivial one : I activated pls in abcranger, and not in abcrf. 
There, I thought of that (lda activated or not) but this is not related.
There is something amiss with the error regression parameters, I *think* that min.node.size in abcrf error regression is 1 instead of 5 because I keep seeing 3 digits in post.proba results for abcrf, and if I multiply by the number of trees (500 there) I got integer results. 
-> What I mean is that if it was *really* min.node.size = 5, by design we should see some by-3 divisions results like 0.836777 sometimes, because for a tree there is at least the possibility of a prediction "falling" in a leave with only three samples (< 5), for example,

**Comment by fradav** [comment]
I think I found the problem : in `SCRIPT_MODEL_CHOICE_RF_short_version_sans_markdown_pour_FD_31_05_2018.R` 

```R
predTest <- predict(model.rf, statobs, dataTrain, ntree, paral = TRUE, min.node.size=1, paral.predict = TRUE)
```

`min.node.size` should be 5, because we are in regression mode, NOT classification.
Stay tuned to see if it solves the problem.

**Comment by fradav** [comment]
This was exactly the problem.
Ks test passed.

![postproba_comparison-minnodesize](https://user-images.githubusercontent.com/701587/60657724-164a8480-9e52-11e9-9b4a-58ff696a7c85.png)
![postproba_boxplots_comparison-minnodesize](https://user-images.githubusercontent.com/701587/60657802-32e6bc80-9e52-11e9-8553-7c3f103b96ed.png)

**Comment by aestoup** [comment]
Warning:

Min node size = 1 for model choice

Min node size = 5 for parameter estimation

So SCRIPT_MODEL_CHOICE_RF_short_version_sans_markdown_pour_FD_31_05_2018.R is OK and you might actually have to change min.node.size from 5 to 1 in your model choice ranger program

**Comment by aestoup** [comment]
OK : conversation with Jean-Michel...pbl: solved (and mistake in my R script= - sorry about that
