### ISSUE TITLE
PyPI packaging

### ISSUE THREAD

**Issue by fradav** [diyabc/abcranger#48]

**Comment by jan-matthis** [comment]
First off, thank you for your work on abcranger and making it public!

I would like to include `pyabcranger` in an open source project. So far, I have been manually building it which requires a full dev setup and would make it complicated for other users to get it up and running. I saw that you have recently released `abcranger` binaries (just tested them, works!). I wanted to ask whether there is any estimate when a`pyabcranger` package with binaries (hosted on GH or PyPI) will be available?

**Comment by fradav** [comment]
Hi Jan,

Thanks for your interest in the library. Linux binary for pyabcranger could be released very easily, is it your main target OS? Windows and macos are tad more complicate to package.

**Comment by jan-matthis** [comment]
Yes, linux is my main target, having a release for that would be great!

**Comment by jan-matthis** [comment]
Apologies for being pushy -- it would be great to have a linux release as soon as possible, is there any way I could be helpful in moving this forward?

**Comment by fradav** [comment]
I completely underestimated how convoluted is the [manylinux](https://github.com/pypa/manylinux) subsystem for PyPi releasing and I'm struggling at this time to integrate  cmake/pybind11/vcpkg C++ packages system nicely for it. It's really an herculean task (the hydra's one, cut one head, two grow back). But I'm sure I will get to the bottom of it.
In the meantime, could you try the wheel in the latest prerelease ?

https://github.com/diyabc/abcranger/releases/tag/1.17

**Comment by jan-matthis** [comment]
Thank you so much for the effort!

I'm running into an issue, here is what I did:
```command line
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

$ conda create -n pyabcranger python==3.8
$ conda activate pyabcranger
$ python --version
Python 3.8.0

$ pip install https://github.com/diyabc/abcranger/releases/download/1.17/pyabcranger-0.0.17-cp38-cp38-linux_x86_64.whl
$ python
Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

>>> import pyabcranger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/jm/miniconda/envs/pyabcranger/lib/python3.8/site-packages/pyabcranger.cpython-38-x86_64-linux-gnu.so)
```

Am I missing some system libraries, or should this in principle be handled by packaging?

**Comment by fradav** [comment]
That's exactly what I feared: the packaging does only pack the .so and any relevant python files (there isn't any in that case) but we are limited to systems with same or superior version of glibc. What distribution are you on?

**Comment by jan-matthis** [comment]
Ugh.. This was on Ubuntu 18.04.5 LTS

**Comment by fradav** [comment]
Hold on, I'm building a wheel on this.

**Comment by fradav** [comment]
https://github.com/diyabc/abcranger/releases/download/1.17/pyabcranger-0.0.21-cp38-cp38-linux_x86_64.whl
Can you try this one ? Manually built from a VM. Full CI build are not working for the moment...

**Comment by jan-matthis** [comment]
This seems to work fine! :)

**Comment by fradav** [comment]
Cool! Do you need any additional builds/targets? If not, I will move on finalizing full automated builds for a proper Pypi release.

**Comment by jan-matthis** [comment]
Python 3.7 (same platform) would be nice to have, but only if it's no hassle. Looking forward to being able to install straight from PyPI, thanks a lot again!

**Comment by fradav** [comment]
No hassle at all, as soon I have access to a console, will do it.

**Comment by fradav** [comment]
Here you are : 
https://github.com/diyabc/abcranger/releases/download/1.17/pyabcranger-0.0.21-cp37-cp37m-linux_x86_64.whl

**Comment by fradav** [comment]
And a 3.6 wheel for good measure : 
https://github.com/diyabc/abcranger/releases/download/1.17/pyabcranger-0.0.19-cp36-cp36m-linux_x86_64.whl

**Comment by jan-matthis** [comment]
Thank you!

**Comment by fradav** [comment]
https://pypi.org/project/pyabcranger/
Enjoy.

**Comment by fradav** [comment]
Now with proper wheels for macos and windows too.
