### ISSUE TITLE
Invalid parameter estimation with microsat header

### ISSUE THREAD

**Issue by fradav** [diyabc/abcranger#50]

**Comment by fradav** [comment]
deuxième issue bidon

**Comment by elombaert** [comment]
[MICROSAT_SCTIPT_MARIE_PODS_ABCRANGER_3_DIYABC3_2020_3_30-1.zip](https://github.com/diyabc/abcranger/files/4408274/MICROSAT_SCTIPT_MARIE_PODS_ABCRANGER_3_DIYABC3_2020_3_30-1.zip)
Voici un projet test pour AbcRanger sur Microsat (2 populations, 1 scénario).
La ligne de commande utilisée pour simuler (après préparation du projet sur DIYABC 2.1.0) :
`../diyabc-linux-20200318-1631 -p ./ -R "" -r 100000 -g 1000 -m -t 4`
Et pour les estimations de paramètre (ici pour N1 et N2 qui donnent des résultats incohérents, cf. priors in UN[10;10000]) :
`../abcranger-linux-outputsarnaud-20200123-1510 -n 10000 -t 1000 -j 4 --parameter N1 --chosenscen 1 --plsmaxvar 0.95 --noob 0 -o estim_param_N1_TEST`
`../abcranger-linux-outputsarnaud-20200123-1510 -n 10000 -t 1000 -j 4 --parameter N2 --chosenscen 1 --plsmaxvar 0.95 --noob 0 -o estim_param_N2_TEST`

**Comment by fradav** [comment]
Tu m'étonnes, on n'avait pas testé avec des paramètres mutationnels et la lecture du reftable donne n'importe quoi sur les paramètres quand il y en a...

**Comment by elombaert** [comment]
Ah oui ! Je me doutais qu'il y avait un lien avec les paramètres mutationnels...

**Comment by fradav** [comment]
Fixed in 8ecc37ec1eac86eea5e80fb9949a528960d75f2f
(binaire dispo dans la release 1.15) 
Je pense que le bug que tu as mentionné ici est lié https://github.com/diyabc/diyabc/issues/20 
Vu que c'est le même code de lecture de reftable partagé avec abcranger...

**Comment by elombaert** [comment]
Merci !
Je vais tester dès que j'ai un peu de temps.

**Comment by fradav** [comment]
Suite à ton dernier mail, je ferme, n'hésite pas à réouvrir l'issue si tu penses qu'il y a encore un problème.
