### ISSUE TITLE
remove constant features for LDA to work and from outputs

### ISSUE THREAD

**Issue by fradav** [diyabc/abcranger#51]
constant features crashed LDA (covariance matrix non-invertible)

**Comment by fradav** [comment]
LDA computed with constant (within class variance < 1e-8) variables removed :
- Fixed in 9b7e0fac6fb88a2154697a3afd2bf11c101af5f4
- Release : https://github.com/diyabc/abcranger/releases/tag/1.16

Normalement, il y a un warning pour chaque variable retirée

**Comment by aestoup** [comment]
cool!
eric va tester ca!

**Comment by elombaert** [comment]
Nouvelle release testée : ça semble tourner parfaitement, avec des messages d'alerte du type "LDA Warning : DTA_1_6 is constant within class, removed."

Par contre, j'ai constaté que les statistiques constantes sont présentes dans la sortie "*.importance", avec des valeurs de 0. Les valeurs de 0 confirment que ces stats n'ont pas eu d'impact sur la génération des forêts, mais ça n'est pas très intuitif de les trouver dans ce fichier puisqu'elles ont, d'après le warning, été "removed".
cf. fichier exemple (les stats VNS_2_3 et DTA_2_3 sont constantes dans le reftable) :
[modelchoice_results_new.importance.txt](https://github.com/diyabc/abcranger/files/4752243/modelchoice_results_new.importance.txt)

**Comment by aestoup** [comment]
Yop = discuté avec Eric ce matin --> recommendation = virer les "stats removed" de toutes les outputs (pour eviter toute ambiguité)

Note: petit detail = cet issue est dans la rubrique closed de abcranger (alors que il faudrait reactiver transitoirement cet issue). Eric ne connait pas la procedure pour ca (moi non plus meme si un simple deplacement pourrait faire le job)

**Comment by fradav** [comment]
En fait si je remplace "removed" par "ignored" ça sera mieux compris ? C'est un peu compliqué pour moi de virer des variables de tout le pipeline de traitement.

**Comment by elombaert** [comment]
Arnaud, je ne sais pas ce que tu en penses, mais je pense personnellement que ça pourrait suffire.

**Comment by aestoup** [comment]
OK je comprends = dans ce cas et pour faire simple et minimiser les ambiguité, va pour ecrire en warning pour chaque variable a pbl XXX: 
"The explanatory statistic XXX is constant within class and was thus ignored during RF treatments"

**Comment by elombaert** [comment]
Je vois également que cette issue n'est pas fermée. Je pense qu'on peut simplement faire ce que Arnaud propose. Une nouvelle release est-elle déjà prête ?
Merci d'avance et bon courage

**Comment by fradav** [comment]
Bonjour,
C'est un oubli de ma part.

C'était prêt dans la dernière release de la semaine dernière comme indiqué dans la note de release:
"More informative message for constant in-class variables filtered out by LDA"

**Comment by elombaert** [comment]
Génial, merci 👍
