### ISSUE TITLE
Generate file summarising the run parameters

### ISSUE THREAD

**Issue by gdurif** [diyabc/abcranger#55]
To know which parameters where used during an analysis (e.g. when looking at result files after a while), it would be interesting to have a small text file generated when `abcranger` is run that summarize the parametrization of the call, i.e.

- For parameter estimation: file `parameter_estimation_analysis_settings.txt` (suggested name) with content
```
Parameter estimation analyses proceeded using:
- Parameter name: XXX
- Scenario X (cf. numero de scenario)
- X simulated datasets
- X trees
- Minimum node size of X
- X summary statistics
- X axes of summary statistics PLS linear combination
- X noise variables
```

- For model choice: file `model_choice_analysis_settings.txt` (suggested name) with content
```
Model choice analyses proceeded from:
- X simulated datasets
- X trees
- Minimum node size of X
- X summary statistics
- X axes of summary statistics linear combination
- X noise variables
```

Thanks

**Comment by fradav** [comment]
- done in e67ba74d23e773f3497a1edc25f2f389401f78f4
- binary release : https://github.com/diyabc/abcranger/releases/tag/1.16.3
