### ISSUE TITLE
Model choice: analyser un sous ensemble des scenarios dans le reftableRF.bin

### ISSUE THREAD

**Issue by aestoup** [diyabc/abcranger#56]
On a quelque fois necessité de focaliser l'analyse RF model choice sur 2 scenarios particuliers (on va dire le 1 et le 3) sachant que on a les data pour 4 scenarios (1, 2, 3 et 4) dans le reftableRF.bin = calculer une probabilté du best scenario si on oppose uniquement les scenarios 1 et 3 (et pas 1, 2, 3 et 4).
Avec le prg R abcrf il suffit de definir deux groupes avec un seul scenario dans chaque groupe = on ecrit:
model.rf <- abcrf(scenario~., dataTrain, group = list(c("1"), c("3")), lda= TRUE, ntree=ntree, paral=TRUE, min.node.size=1, save.memory=FALSE)
On fait bien alors une analyse avec groupe 1 = scenario 1 et groupe 2 = scenario 3.
J'ai tenté de faire ca avec abcranger et ca semble planter. J'ai lancé l'instruction suivante:
./abcranger-linux-20200611-1621 -n 12000 -t 1000 -g "1;3" -j 32 -o modelchoice_test
Ca plante. Peut etre que c'est parceque je n'ai que 4000 data pour les scenarios 1 et 3 (cf. 2000 data par scenario).
Mais meme en mettant -n 4000 ca plante.
Note: je tente ca sur l'exemple SNP poolseq MER.
Bref: comment faire pour analyser qu'un sous-ensemble des scenarios presents dans un reftableRF.bin?
Si on peut faire ca ca serait tres utile.
J'espere que ca t'inspire.

**Comment by fradav** [comment]
- done in e67ba74d23e773f3497a1edc25f2f389401f78f4
- binary release : https://github.com/diyabc/abcranger/releases/tag/1.16.3

**Comment by aestoup** [comment]
Suoer FD et bravo: je fais un text ASAP
