### ISSUE TITLE
Numerical Output to do the equivalent of FIGURE 2 of the MER ms.

### ISSUE THREAD

**Issue by aestoup** [diyabc/abcranger#59]
Can you generate in an additional output file the numerical outputs so that Ghislain can produce the equivalent of FIGURE 2 of the MER ms = FIGURE 2. Projection of the PoolSeq datasets from the training set on a single LDA axis when analyzing the two groups of scenarios (A) or on the first two LDA axes when analyzing the six scenarios separately (B).

This is a nice and useful figure!

**Note: Apres discussion avec Ghislain, il semble IN FINE (et contrairement a ce que je t'ai dit hier) preferable que Ghislain produise les graphiqcal outputs a partir des sorties numeriques de abcranger (pour plusieurs raisons que je pourrai t'expliquer).**

En fait il manque juste les outputs numerique pour faire l'equivalent de la FIGURE 2 MER.
Le reste semble etre produit dans tes sorties numeriques (c'est cool et bravo!)

**Comment by fradav** [comment]
En gros il manque juste les valeurs des axes LDA ?

**Comment by fradav** [comment]
- done in e67ba74d23e773f3497a1edc25f2f389401f78f4
- binary release : https://github.com/diyabc/abcranger/releases/tag/1.16.3

**Comment by aestoup** [comment]
Cool (et merci pour Ghislain).
On va pouvoir faire toutes les sorties graphiques a partir des outputs de abcranger: excellent!
Je test le binary ASAP.
