### ISSUE TITLE
oob error computation by number of trees is wrong

### ISSUE THREAD

**Issue by fradav** [diyabc/abcranger#61]
In parallel setting, the cumulative OOB error rate is unsorted, the OOB error rate vs number of trees isn't clearly decreasing.

![false](https://user-images.githubusercontent.com/701587/91432431-02d25800-e862-11ea-82ca-0c0a522e2bba.png)

**Comment by fradav** [comment]
Fixed in e45d3eb
Releases : https://github.com/diyabc/abcranger/releases/tag/1.16.5

![ok](https://user-images.githubusercontent.com/701587/91434434-18954c80-e865-11ea-8c11-55265dea9f6b.png)

**Comment by gdurif** [comment]
oob error is still wrong for parameter estimation.

**Comment by fradav** [comment]
Right!
Fixed in : 92eccc0 (look at [Population Genetics notebook](https://github.com/diyabc/abcranger/blob/master/notebooks/Population%20genetics%20Demo.ipynb), before the final distribution
Releases : same as before
