### ISSUE TITLE
Dossier qui bug sous windows pour abcranger_AE_pour_review_MER.exe  (de meme que precedents execurables windows)

### ISSUE THREAD

**Issue by aestoup** [diyabc/abcranger#70]
J'ai produit une simulation replicat d'un reftable pour exemple Human a priori clean sous linux (ma machine linux remarche enfin). Objectif verifier clean les resultats sur l'exemple human.

J'ai donc un headerRF.txt et un reftabkleRF.bin et un statobs.txt

Je te mets ces trois fichiers en PJ (cf. fichier zippé = Human_new_stats_5000SNP_2000simPerScenario_plus1000_MAF1%_REPLICAT_produit_sous_Linux.zip)

Quand je lance sous windows l'exe windows
abcranger_AE_pour_review_MER.exe -n 12000 -t 1000 -j 8 -o ABCRF_modelchoice_results_run1
Ca bug (et s'arrete) des la lecture du headerRF !!!

Quand je lance sous linux l'exe windows
./abcranger_AE_pour_review_MER -n 12000 -t 1000 -j 8 -o ABCRF_modelchoice_results_run1
Ca run parfaitement

Quand je lance mon script R pour model choice ca run parfaitement

Bref, un pbl avec la version sous windows (j'ai le meme pbl avec l'exe precedent!)
[Human_new_stats_5000SNP_2000simPerScenario_plus1000_MAF1%_REPLICAT_produit_sous_Linux.zip](https://github.com/diyabc/abcranger/files/5440200/Human_new_stats_5000SNP_2000simPerScenario_plus1000_MAF1._REPLICAT_produit_sous_Linux.zip)

J'ai beau regarder le headerRF.txt je le trouve nickel!

Etonnant non ? Ca serait cool tu pîges ce qui gene sous windows dans ce dossier.

**Comment by fradav** [comment]
C'est un problème de parsing du header.txt spécifique à windows que j'espérais avoir résolu depuis longtemps, avant qu'il ne remonte sa tête hideuse... J'ai une parade qui allonge les temps de compilation considérablement, mais bon. T'auras un binaire tout neuf d'ici demain normalement.

**Comment by fradav** [comment]
Fixed with abcranger_AE_pour_review_MER-corrige.exe (same release as before)
