### ISSUE TITLE
Formating issue in modelchoice_out.lda

### ISSUE THREAD

**Issue by gdurif** [diyabc/abcranger#73]
Alignment problem starting from line 3 in `modelchoice_out.lda` (simulation LDA coordinates). The trailing spaces at the beginning of the lines make it difficult for the file to be read from R.

```
$ head modelchoice_out.lda

# First line is observed data
-6.79535  1.20037  8.58463  2.05981  14.0425
    -7.17716     -1.07297      8.86666      2.23932      12.3663
    -7.65102      0.13306      7.37678      2.91073      13.4171
    -7.06504       1.0655      7.49974      2.39359      14.0281
    -6.62584     0.427253      7.98394      2.08683      13.7528
    -6.91117      1.01163        8.203      1.42321      13.7882
    -5.08759      1.36191      9.99218       3.7454      16.5691
    -6.25676      0.45838      9.07217      2.82503       14.154
    -5.86496     0.263481      7.40707      2.28433      13.6808
```

**Comment by gdurif** [comment]
In addition, a non varying separator (e.g. `;`) would be easier to handle in R

**Comment by fradav** [comment]
Release https://github.com/diyabc/abcranger/releases/tag/v1.2.49
Note that the number of statobs rows may be larger than one, this is in prevision of the multi target (WIP) version.

It is enclosed in parenthesis in the first comment.

**Comment by fradav** [comment]
Tested R `read.table("modelchoice_out.lda")` without any issues.
