### ISSUE TITLE
Estimate results were overlapped.

### ISSUE THREAD

**Issue by xiekunwhy** [diyabc/abcranger#79]
Hi,

Why don't use tab to seperate results? And the Quantile_0.95 and Variance numbers are connected and difficult to distinguish.
   Expectation        Median Quantile_0.05 Quantile_0.95      Variance
   8678.918750   8690.634989   2834.611872  13007.3906256924204.116055

Best,
Kun

**Comment by fradav** [comment]
Fixed in 9b4adff
Release https://github.com/diyabc/abcranger/releases/tag/v1.2.50
