### ISSUE TITLE
How to get posterior probabilities of each scenario using abcranger?

### ISSUE THREAD

**Issue by xiekunwhy** [diyabc/abcranger#80]
Hi,

Can abcranger provide posterior probabilities of each scenario when doing model choice?

Like results in some papers,
table 4 in https://peerj.com/articles/9980/
Figure 7 in https://peerj.com/articles/7987/

Best,
Kun

**Comment by fradav** [comment]
Only the posterior probability of the selected model is computed and it is by design on ABC-Random Forest methodology, see Pudlo, Pierre, et al. "Reliable ABC model choice via random forests." Bioinformatics 32.6 (2016): 859-866.

Regards
