### ISSUE TITLE
Identify group setting ('-g/--groups') in modelchoice_out.setting

### ISSUE THREAD

**Issue by gdurif** [diyabc/abcranger#82]
Examples of possible output tin modelchoice_out.setting:

- All scenarii and no group : `Compared scenarios: 1;2;3;4;5;6`
- All scenarii and two groups : `Compared scenarios: 1,2,3;4,5,6`
- Two scenarii and no groups : `Compared scenarios: 1;4`
etc.

**Comment by fradav** [comment]
Fixed in 041dbb3
Release : https://github.com/diyabc/abcranger/releases/tag/v1.2.54
