### ISSUE TITLE
Segmentation fault (core dumped) abcranger-linux-v1.2.60

### ISSUE THREAD

**Issue by phrh** [diyabc/abcranger#88]
hello, 
I am getting the following error by running on a linux pc. I run the TOY_EXAMPLE3_SNP_INDSEQ_scenario3_MER_light_configuration without any problem. Can you help me?

``
./abcranger-linux-v1.2.60 -n 12000 -t 1000 -j 8 -o modelchoice_results_no_grouping
> Model Choice <
///////////////////////////////////////// read headers
read headers done.
///////////////////////////////////////// read reftable
read reftable done.
Segmentation fault (core dumped)
``

**Comment by fradav** [comment]
Hello,

I'm currently on vacation until mid July. In the meantime, could you provide the reftable and the header files somewhere? I think you may attach the reftable there if it isn't too big.

Regards,

**Comment by phrh** [comment]
Hi, 
In this link you will find both files (https://drive.google.com/drive/folders/1h66MLihLCYN8_Dfk07xidHBLAI3QSQX7?usp=sharing). One more question, to run the previous diyabc (2014) from this command line version, I just used the previous header file and run the following lines ?

`
./diyabc-RF-linux-v1.1.24 -p ./ -R ALL -r 6000 -g 50 -m -t 5 > primerpaso.txt
./abcranger-linux-v1.2.60 -n 6000 -t 1000 -o modelchoice_results_no_grouping      
`

**Comment by fradav** [comment]
> Hi, 
> In this link you will find both files (https://drive.google.com/drive/folders/1h66MLihLCYN8_Dfk07xidHBLAI3QSQX7?usp=sharing). One more question, to run the previous diyabc (2014) from this command line version, I just used the previous header file and run the following lines ?
> 
> `
> ./diyabc-RF-linux-v1.1.24 -p ./ -R ALL -r 6000 -g 50 -m -t 5 > primerpaso.txt
> ./abcranger-linux-v1.2.60 -n 6000 -t 1000 -o modelchoice_results_no_grouping      
> `
> 

If your header is intended to work with diyabc circa 2014, you'll probably run into incompatibilities with more recent version of diyabc, the naming scheme of summary statistics changed. You have two options:

- generate your reftable with the old diyabc and manually add all stats in the header you want to appear in the RF pipeline with abcranger
- manually delete all summary stats from the header (beware the stats count and the last line) and let the `-R ALL` do its magic to generate all possible stats.

**Comment by phrh** [comment]
No, I want to work with diyabc-rf. If you need any additional file please let me know

 But I had an old header with smaller dataset, and I wanted to make it work with the new version.

**Comment by phrh** [comment]
I found an error in the .snp file, I am sorry. Now it works, and I am able to choose a scenario. I have one more question is there any help for the abcranger-linux-v1.2.60 ?

**Comment by fradav** [comment]
Hello, I'm glad you solved the problem. You'll have to be a little more specific about the help you're seeking, because the command line tool is documented at https://github.com/diyabc/abcranger and the general concepts are explained in our paper : 

Collin, François‐david, et al. "Extending Approximate Bayesian Computation with Supervised Machine Learning to infer demographic history from genetic polymorphisms using DIYABC Random Forest." Molecular Ecology Resources (2021).
