### ISSUE TITLE
abcrangers treatment (parameter estimation) does not work when using statobsRF.txt produced with the beta version diyabc-RF-windows-v1.1.36.exe

### ISSUE THREAD

**Issue by aestoup** [diyabc/abcranger#97]
Hi Fradav,
You provided me a few months ago with a beta version of diyabc (diyabc-RF-windows-v1.1.36.exe)  with different options reactivated and with values of parameters and stats written using the scientific notation (i.e. exponential notation). 
It turns out that abc-ranger is not able to do parameter estimation from the outputs produced by this beta version = it says "wrong number of sumstats in the file statobsRF.txt". I know that the number of sumstat is actually correct and the r-package abcrf has no pbl with the outputs.
Is this because abc-ranger does not cope with scientific notations of statobs values ?
Can you please patch that? (note: I believe that a scientific notation should be better for the next diyabc-RF version).
By advance thank you
A.
PS: see the statobsRF.txt HeaderRF.txt and reftableRF.bin files with only 500 particules to make it easily tranferable
zipped in 
[ABCRF_test_header_12_parametres.zip](https://github.com/diyabc/abcranger/files/14335649/ABCRF_test_header_12_parametres.zip)

 (attached)

**Comment by fradav** [comment]
Fixed with https://github.com/diyabc/abcranger/releases/tag/v1.16.69
