### ISSUE TITLE
comad line exception

### ISSUE THREAD

**Issue by vincenzolandi** [diyabc/abcranger#99]
Hello i am trying to implement a previous run made with the GUI version of DYABC...I load in the server folder the following files: header.rf and myfile:DIYABC.snp file.  doing this: diyabc-RF-linux-v1.1.27 -p ./ -n "t:4" i produced a RNG_state_0000.bin.
Then doing this: diyabc-RF-linux-v1.1.27 -p ./ -d a:pl i get an error:
"
debut
headerRF.txt found, choosing it over header.txt
option -d a:pl      a:pl
./set2b.DIYABC.snp.bin
set 2 <NM=1.0NF>
Fichier ./set2b.DIYABC.snp : SNP
lecture du fichier binaire
smaf=0.05
THIS->MAF=0.05
sexratio=0.5
nloc=7369
nsample=5
 type 0   catexist =1
 type 1   catexist =0
 type 2   catexist =0
 type 3   catexist =0
 type 4   catexist =0
type 0
224   28   90   116   44
this->maf=0.05
dans libin
this->locus[0].haplosnp[0][0]=1
sexratio=0.5
fin de la lecture du fichier binaire
avant missingdata
apres missingdata
nparamtot=18
nstat=292
----------------------------------------apres readHeaderDebut
4 scenario(s)
----------------------------------------apres readHeaderScenarios
historical parameters priors (18,8)
----------------------------------------apres readHeaderHistParam
fichier SNP dans redheaderLoci
7370 <A> G1 from 1
prem = 0
groupe[1].nloc=7370
----------------------------------------apres readHeaderLoci

!!! I have caught an exception which is:
Erreur dans readheaders().
Not enough loci of type <A> found in the datafile from position 0. This is perhaps due to the elimination of 1 monomorphic loci from the original dataset."

it is very strage to me as this file have been analzed succesffully with GUI version

thnak you

**Comment by fradav** [comment]
Hi, this is an issue for diyabc, the simulator, please open the issue in correct repository, thanks!
